### ISSUE TITLE
win无法测试，请问是哪里有问题

### ISSUE THREAD

**Issue by PaleMooon** [mobier/shadowsocksr-speed#17]
C:\Users\hong>z:

Z:\>cd ss

Z:\SS>python shadowsocksr-speed_win.py gui-config.json
Traceback (most recent call last):
  File "shadowsocksr-speed_win.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Z:\SS>
不懂编程，求解答

**Comment by Nigel-NI** [comment]
输入pip install requests

**Comment by mobier** [comment]
装一下requests的库，是python3吗




            
            
                
                    
                            
                                
                            
                            
                                jie lin
                            
                    
                        
                            
                                    邮箱：vxxwej@gmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年02月05日 22:08，NigelSong 写道： 输入pip install requests

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mobier/shadowsocksr-speed","title":"mobier/shadowsocksr-speed","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mobier/shadowsocksr-speed"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NigelSong in #17: 输入pip install requests"}],"action":{"name":"View Issue","url":"https://github.com/mobier/shadowsocksr-speed/issues/17#issuecomment-460650275"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mobier/shadowsocksr-speed/issues/17#issuecomment-460650275",
"url": "https://github.com/mobier/shadowsocksr-speed/issues/17#issuecomment-460650275",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by PaleMooon** [comment]
全部节点只有localping，没有测速，显示fail。
还是这样的问题 
@NigelSong  你解决了吗

**Comment by Nigel-NI** [comment]
没有解决，我尝试了各种方法，但至今无解，不了了之。可以参考：https://github.com/mobier/shadowsocksr-speed/issues/14

**Comment by ghost** [comment]
同样都是fail的问题，requests都已经正确安装，无法正常工作，win10用户·

**Comment by kingofotaku** [comment]
和楼上各位同样的问题，我甚至还尝试了在管理员模式下的cmd中运行脚本（为此还把脚本里引用的路径都改成绝对路径了）结果还是出这个错，怎么测都是fail。

**Comment by mobier** [comment]
都有出现`[WinError 10061]`报错吗

**Comment by mobier** [comment]
@PaleMooon 试试运行这个`https://github.com/sivel/speedtest-cli`

**Comment by kingofotaku** [comment]
> 都有出现`[WinError 10061]`报错吗

是的，就是这个错误

**Comment by kingofotaku** [comment]
问题已有解决方法#18
