### ISSUE TITLE
IPv6 not support

### ISSUE THREAD

**Issue by ttmoresun** [mobier/shadowsocksr-speed#42]
mac os 下IPv6 not support，而且测得结果都是0，只有network里边显示的状态是正常的

**Comment by loveuqian** [comment]
我这边也是这个情况

![image](https://user-images.githubusercontent.com/9745332/59480111-f1d23c80-8e91-11e9-836e-ce8485a1a1b1.png)

**Comment by li-yuening** [comment]
Same issue here. All failed except one.

**Edit: **
'IPv6 not support' has no relationship with the failure. It's a very normal log info.

For me, I cannot run YouTube speed test. The reason is in `youtube_speed.py`. `pyvirtualdisplay` needs the requirement of `X11` which has been removed in recent macOS versions. The solution is [here](https://github.com/Greenwolf/social_mapper/issues/50). When running `youtube_speed.py`, you should find that your Chrome is opened by `selenium`. Everything will be done, such as button clicks, context menu opens, automatically.
